### ISSUE TITLE
rain/snow depth?

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [bogstandard/rl-weather#12]
a suggestion would be to mix different sizes of particles and make them move faster or slower depending on thier size to give the rain and snow effect a little more depth

**Comment by bogstandard** [comment]
This should be fairly easy to implement, if you want to make a pull request you're more than welcome. Just be aware that it will still need to reflect the user defined Gravity and Sizes, so some factor of difference will have to be decided.

**Comment by ipkpjersi** [comment]
I may give this a whirl some time if I manage to find some free time unless someone beats me to it.

**Comment by bogstandard** [comment]
I'm giving this an attempt in my free time, but whoever gets their first or has the best solution wins :)

**Comment by ipkpjersi** [comment]
I'm thinking if we have a minimum size and a maximum size as two options with a random size toggle option then we could just generate random sized snow between min and max. That'd be more realistic at least.

**Comment by bogstandard** [comment]
I've done a rough implementation of this on the new [particle-depth branch](https://github.com/bogstandard/rl-weather/tree/particle-depth). Works as following:
- New Drops get a random `.depth` int value between 1 and 5. I'm not sure this needs to be customisable, it gets a bit silly feeling outside the 5 bracket.
- The greater the `drop.depth` the closer to the camera the drop is.
- The closer to the camera the more the drop is larger and faster.
- Rain config values have been split into thickness and length.
- I've removed the confusing for loop on the rain rendering.

It's not the best the best implementation and it works better for snow, rain it's not really noticeable (honestly I've never liked the rain effect I made much anyway, if its able to be overhauled I'd be more than accommodating).

**Comment by ipkpjersi** [comment]
The depth actually looks really good.

I've gone ahead and fixed the rain on a new branch, you can actually see the different sized rain really well now, it looks quite nice imo especially with the dynamic gravity: 
![](https://i.imgur.com/v13F2fy.png) 

Feel free to test it out, I think it's a pretty decent improvement.

I'm quite happy with this plugin currently, I'm hoping to have some time in December to rewrite the sounds in this plugin to use an MP3 library or something similar instead of the default WAV audio, so that'll be cool.

**Comment by bogstandard** [comment]
Nice one with the depth fix, I've just reverted your change to the rain x2, x1 stuff, it needs to be the previous way because it doesn't match the wind direction (left to right) otherwise.

I'll merge this into master and update the Plugin Hub this week hopefully.

**Comment by ipkpjersi** [comment]
For some reason, correcting the direction completely changes the size of the droplets, and it makes them way bigger (longer): 
![](https://i.imgur.com/1rnrZrb.png)

Maybe that's intended though, since you can always manually change the length via options and then it looks fine: 

![](https://i.imgur.com/mR7dBwS.png)

Just something I noticed, seems like it's probably fine though.

**Comment by bogstandard** [comment]
This is all merged in now, big thanks @Jin-Jiyunsun for promoting a cool idea & giving it a try! Big thanks to @ipkpjersi for helping with this one and the other sound issues! 

Gonna be closing this one since the main topic has been completed 🥳
